# Generated by Django 2.0.2 on 2019-02-14 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RFC', models.CharField(max_length=10, null=True)),
                ('numero_de_empleado', models.IntegerField(null=True)),
            ],
            options={
                'permissions': (('is_admin', 'Is_Admin'),),
            },
        ),
    ]
