# Generated by Django 2.0.2 on 2019-04-15 15:58

import administrador.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RFC', models.CharField(max_length=15, null=True)),
                ('numero_de_empleado', models.IntegerField(null=True)),
                ('foto_ine', models.FileField(null=True, upload_to='profiles')),
                ('e_firma_key', models.FileField(null=True, upload_to=administrador.models.upload_e_firma)),
                ('e_firma_cer', models.FileField(null=True, upload_to=administrador.models.upload_e_firma)),
                ('puesto', models.CharField(max_length=20, null=True)),
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('is_admin', 'Is_Admin'), ('is_seller', 'Is_Seller')),
            },
        ),
    ]
