# Generated by Django 2.0.2 on 2019-02-15 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0002_administrador_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='RFC',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
