# Generated by Django 2.0.2 on 2019-02-20 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0004_archivos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrador',
            options={'permissions': (('is_admin', 'Is_Admin'), ('is_seller', 'Is_Seller'))},
        ),
        migrations.AddField(
            model_name='administrador',
            name='e_firma',
            field=models.FileField(null=True, upload_to='profiles'),
        ),
        migrations.AddField(
            model_name='administrador',
            name='foto_ine',
            field=models.FileField(null=True, upload_to='profiles'),
        ),
        migrations.AddField(
            model_name='administrador',
            name='puesto',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
