# Generated by Django 2.0.2 on 2019-02-25 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_cliente_contador'),
        ('administrador', '0005_auto_20190220_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivos',
            name='contador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contadorACargo', to='administrador.Administrador'),
        ),
        migrations.AddField(
            model_name='archivos',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='FDI', to='usuario.Usuario'),
        ),
        migrations.AlterField(
            model_name='archivos',
            name='archivo',
            field=models.FileField(upload_to='documentos/<function user_ruta_directorio at 0x7f35f8e3f2f0>'),
        ),
    ]
