# Generated by Django 2.0.2 on 2019-02-26 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0006_auto_20190225_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivos',
            name='archivo',
            field=models.FileField(upload_to='documentos/<function user_ruta_directorio at 0x7f9b6ba692f0>'),
        ),
    ]
