# Generated by Django 2.0.2 on 2019-02-27 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_cliente_contador'),
        ('administrador', '0008_auto_20190226_0748'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subido_el', models.DateTimeField(auto_now_add=True)),
                ('archivo', models.FileField(upload_to='superadmin/')),
                ('contador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contadorACargo', to='administrador.Administrador')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='FDI', to='usuario.Usuario')),
            ],
        ),
        migrations.RemoveField(
            model_name='archivos',
            name='contador',
        ),
        migrations.RemoveField(
            model_name='archivos',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Archivos',
        ),
    ]
