# Generated by Django 2.0.2 on 2019-02-27 18:04

import administrador.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0009_auto_20190227_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='archivo',
            field=models.FileField(upload_to=administrador.models.upload_to),
        ),
    ]
