# Generated by Django 2.0.2 on 2019-03-07 17:57

import administrador.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_cliente_contador'),
        ('administrador', '0010_auto_20190227_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subido_el', models.DateTimeField(auto_now_add=True)),
                ('xml', models.FileField(upload_to=administrador.models.upload_to)),
                ('pdf', models.FileField(upload_to=administrador.models.upload_to)),
                ('contador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contadorACargo', to='administrador.Administrador')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='FDI', to='usuario.Usuario')),
            ],
        ),
        migrations.RemoveField(
            model_name='archivo',
            name='contador',
        ),
        migrations.RemoveField(
            model_name='archivo',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Archivo',
        ),
    ]
