# Generated by Django 2.0.2 on 2019-02-17 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nombre_usuario',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
