# Generated by Django 2.0.2 on 2019-02-15 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='RFC',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
