# Generated by Django 2.0.2 on 2019-02-20 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_auto_20190215_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='direccion_fiscal',
            field=models.CharField(max_length=125, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='e_firma',
            field=models.FileField(null=True, upload_to='profiles'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='razon_social',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipo_persona',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
