# Generated by Django 2.0.2 on 2019-02-25 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_auto_20190220_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='contador',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.Usuario'),
        ),
    ]
